name: Deploy site to production bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUCKET: prod-bucket-davidainslie

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build site
        run: |
          npm install
          npm ci
          npm run build

      - name: Deploy files to prod bucket
        run: aws s3 cp public s3://${{env.BUCKET}}/ --recursive --acl public-read
